.TH SUP 1

.SH NAME
sup \- manage git submodules

.SH SYNOPSIS
.B sup [OPTIONS] \fICOMMAND\fR [ARGUMENTS]

.SH OPTIONS
.TP 
\-h \t print the usage
.TP 
\-n \t dry run by not making changes
.TP 
\-q \t operate quietly
.TP 
\-v \t verbose output
.TP 
\-x \t echo git commands

.SH COMMANDS
.TP
add <repository> [\-\-] [<path>]
XXXXX
.TP
status [\-\-] [<path>]
XXXXX
.TP
remote [\-\-] [<path>] [<repository>]
XXXXX
.TP
pull [\-\-] [<path>]
XXXXX
.TP
checkout [\-\-] [<path>]
XXXXX
.TP
clean [\-\-] [<path>]
XXXXX
.TP
rm [\-\-] [<path>]
XXXXX
